version: Build {build}

skip_non_tags: true

build:
    verbosity: minimal

environment:
    matrix:
        - PYTHON: "C:\\Python35"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "pip install -r requirements.txt"
    - "pip install pyinstaller"
    - "choco install -y InnoSetup"

before_build:
    - powershell -command "-join (\"version = `'\", $(git describe), \"`'\") | Out-File -encoding utf8 PyEveLiveDPS\\version.py"

build_script:
    - "pyinstaller setup-standalone.spec"
    - "pyinstaller setup-for-installer.spec"
    - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
    - "iscc InstallerSetup.iss"

after_build:
    - "mv dist\\PELD-standalone.exe PELD-standalone-%APPVEYOR_REPO_TAG_NAME%.exe"
    - "mv dist\\PELD-installer.exe PELD-installer-%APPVEYOR_REPO_TAG_NAME%.exe"

artifacts:
    - path: PELD-standalone*.exe
      name: PELD-standalone
    - path: PELD-installer*.exe
      name: PELD-installer

deploy:
    - provider: GitHub
      description: ""
      artifact: /PELD.*/
      draft: false
      prerelease: false
      on:
        appveyor_repo_tag: true
      auth_token:
        secure: YiOZJy8/2E9IgFGzFPYkyKjmH4vUBfmam6MDFGyk4bSlS4861xl9cC8owmH9LYnR